# Built with Jekyll 3.2.0

# Setup
title:               FEniCS
tagline:             'Finite Element, Computer Sofware'
logo:		     '/assets/img/fenics_logo2.png'
description:         'A workshop for FEniCS 2018.1.0'
url:                 'https://vanessanehruji.github.io/fenics_workshop'
baseurl:             '/fenics_workshop'

# About/contact
author:
  name:              Marin Lauber, Vanessa Nehruji
  url:               https://github.com/vanessanehruji
  email:             vanessa.nehruji@gmail.com

# Color scheme. Options: red, orange, magenta, cyan, blue, brown
color-scheme:

# Permalinks
permalink: pretty
permalink: /:title/

# Set encoding to UTF-8
encoding: utf-8

# Collections for texts
collections:
  texts:
    output: true

# Markdown specs
markdown: kramdown

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  footnote_backlink: "&#x21a9;&#xfe0e;"
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Exclusions from the final site
exclude:
  - optional
  - vendor

# Theme
theme: "ed."
